### ISSUE TITLE
Error al cargar la configuracion de qtile en debian 9

### ISSUE THREAD

**Issue by AlphaTechnolog** [antoniosarosi/dotfiles#11]
He intentado clonar tu configuracion de qtile, pero he tenido un problema. Consiste en que al iniciar qtile... obtengo la configuracion por defecto de qtile, con un mensaje que dice: `Config Err!`, intente ejecutando la configuracion con `cd ~/.config/qtile ; python3 ./config.py`, y obtengo el siguiente error:

```
Non-config.Match objects in float_rules are deprecated
Traceback (most recent call last):
  File "./config.py", line 14, in <module>
    from settings.widgets import widget_defaults, extension_defaults
  File "/home/thecoderpro/.config/qtile/settings/widgets.py", line 64, in <module>
    widget.Pacman(**base(bg='color4'), update_interval=1800),
  File "/usr/local/lib/python3.7/dist-packages/qtile-0.16.2.dev190+ga7d27ef6-py3.7-linux-x86_64.egg/libqtile/utils.py", line 226, in __getattr__
    raise AttributeError
AttributeError
```

Estas son algunas capturas:

En la barra se ve el error: `Config Err!`
![1](https://user-images.githubusercontent.com/54639968/104972471-3e63ef00-59c8-11eb-95ce-dc49f0166fc2.png)

El output del comando anteriormente mencionado:
![2](https://user-images.githubusercontent.com/54639968/104972515-5d628100-59c8-11eb-81e8-5dd80035d23f.png)

**Comment by antoniosarosi** [comment]
Seguramente el widget de Pacman ya no sirve, habrán puesto otro nuevo, prueba ir al archivo ```settings/widgets.py``` y quitar el widget de Pacman. Para probar configs de gestores de ventanas puedes utilizar (Xephyr)[https://wiki.archlinux.org/index.php/Xephyr_(Espa%C3%B1ol)], es bastante cómodo. En Debian creo que se instala con ```apt install xserver-xephyr```.

**Comment by AlphaTechnolog** [comment]
Bien... ahora en mi terminal recibo lo siguiente: `Non-config.Match objects in float_rules are deprecated
Unmet dependencies for 'libqtile.widget.net.Net': No module named 'psutil'`..., pero ahora se asi :)

![Pantallazo-2021-01-18 20-19-21](https://user-images.githubusercontent.com/54639968/104973234-779d5e80-59ca-11eb-8f4b-dd3e1f04668d.png)

creo que tengo un problema con la net, pd: uso wifi

**Comment by antoniosarosi** [comment]
No no, no tienes un problema, te falta ese paquete.

```pip install psutil```

**Comment by AlphaTechnolog** [comment]
Perfecto muchas gracias ahora si... una pregunta rapida: como cambio el tema a material ocean

**Comment by antoniosarosi** [comment]
Está explicado [aquí](https://github.com/antoniosarosi/dotfiles/tree/master/.config/qtile#Themes), básicamente abres el archivo ```~/.config/qtile/config.json``` o lo creas si no existe, y pones:

```json
{
    "theme": "material-ocean"
}
```

**Comment by antoniosarosi** [comment]
Después tienes que reiniciar con control mod R

**Comment by AlphaTechnolog** [comment]
Muy bien muchisimas gracias crack!
