### ISSUE TITLE
Error con los monitores

### ISSUE THREAD

**Issue by EdwinJPA** [antoniosarosi/dotfiles#17]
Ayuda, he intentado de varias maneras para configurar el arandr, mientras configuro la sesión todo bien, el problema es que cuando reinicio se pierde la configuración, lo he colocado en .profile en autorun, en .xprofile, y nada, se supone que la configuración está bien porque es la misma que me genera el arandr, gracias.

**Comment by edwz-dev** [comment]
A la final fue una dependencia de lightdm, cree el archivo .profile en ~/ y le di permisos de ejecución con chmod +x script.sh, con el siguiente código
`sleep 3
/home/username/.config/qtile/arandr/monitor.sh` abajo del sleep es la ruta, y el script fue generado con arandr, después MOD + CTRL + R y reboot al pc y listo, funciona
