### ISSUE TITLE
[BUG] not urgent: Forma extraña "M" aparece en la parte superior de la pantala.

### ISSUE THREAD

**Issue by pablocorbalann** [antoniosarosi/dotfiles#19]
Estaba probando la configuración de Qtile de este repositorio, la primera vez que probé esta configuración, funcionó todo perfectamente, la segunda vez (después de reiniciar el ordenador) **aparecieron unas formas extrañas en la barra superior (donde se encuentra la información de red**, los layouts etc.)

Es una forma curiosa cuanto menos, con forma de vector en "m" (vs. barra superior en capura). Voy a ver si lo consigo arreglar, en caso de que lo consiga solucionar lo escribiré en este hilo. 

Si alguien sabe algo o le ha pasado algo similar, se agradece cualquier tipo de ayuda. Puede que sea cosa de mi ordenador o de mi tarjeta gráfica.

![m_extragna](https://user-images.githubusercontent.com/63709477/114194161-7fc4c480-994f-11eb-8f1e-d1f3cba88774.png)

**Comment by antoniosarosi** [comment]
No, el problema es la fuente. Tienes que usar una [Nerd Font](https://www.nerdfonts.com/font-downloads), en mi config estoy usando UbuntuMono, lo puedes descargar [aquí](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Ubuntu.zip) y después descomprimelo dentro de ```~/.local/share/fonts```, crealo si no existe.

**Comment by pablocorbalann** [comment]
Vale pues esto ha sido bastante más facil de solucionar de lo que pensaba, me imaginaba que sería algun problema importante de la gráfica o cualquier cosa y cambiando el caracter del widget powerline de un triangulo a un espacio se ha solucionado (aunque ahora mismo no aparece el triángulo en la barra, personalmente me gusta más así). El archivo es `~/.config/qtile/settings/widgets.py` (vs. captura de pantalla). Supongo que será algo relaccionado con la fuente. No le doy mas importancia, simplemente que esto quede guardado para la historia por si a alguien le pasa y tal. 

Ahora mismo la fuente que estoy usando es `JetBrains mono regular` (si, es nerd font)
![powerline](https://user-images.githubusercontent.com/63709477/114196296-85bba500-9951-11eb-83e3-20d6d6c0f364.png)

**Comment by antoniosarosi** [comment]
Prueba lo que dije para ver si se arregla con eso, aunque luego le quites los triángulos.

**Comment by pablocorbalann** [comment]
He instalado ubuntu mono (de nerd fonts) y los triangulos ya funcionan (si los vuelves a incluir en el script de python). Sin embargo no estoy seguro de por qué sucede esto, es decir en mi ordenador tengo numerosas fuentes de nerd font instaladas, como JetBrainsMono, FiraCode o Caskaydia, y los iconos de los workspaces funcionan correctamente gracias a estas fuentes, hay alguna posibilidad de que los triangulos sean caracteres diferentes en algunas fuentes (no se exactamente como funcionan los hex en nerd fonts)

**Comment by antoniosarosi** [comment]
```python
widget_defaults = {
    'font': 'UbuntuMono Nerd Font Bold',
    'fontsize': 14,
    'padding': 1,
}
```
Por esto. Cambialo por Fira o la que sea en ```settings/widgets.py```y en teoría debería funcionar.

**Comment by pablocorbalann** [comment]
De acuerdo, no había visto esa parte del código. Ya parece funcionar con el resto de fuentes. En este caso jet brains mono:
![triangles](https://user-images.githubusercontent.com/63709477/114211763-544ad580-9961-11eb-9d80-e5aac170fb70.png)
Gracias por la ayuda.
