### ISSUE TITLE
Error al compartir pantalla en apps como discord, meet

### ISSUE THREAD

**Issue by edwz-dev** [antoniosarosi/dotfiles#20]
Hola, tengo un problema a la hora de compartir pantalla en algunas apps como discord o meet, el problema es que al intentar compartir una pantalla en específico, ya sea la del portatil o la del monitor, no me deja seleccionar una en específico, al compartir se muestran ambas pantallas y no tengo opción de selección, ¿Cómo podría arreglarlo?
Aquí una imágen para mejor entendimiento del problema:

**En meet:**

[Selección de pantalla](https://imgur.com/X3R6fTb)

[Cuando se está compartiendo la pantalla](https://imgur.com/c0G7zQv)

**En discord:**
Aquí es un poco diferente, ya que me detecta las pantallas pero a la hora de mostrarlas me sigue generando el error.

[Selección de pantalla](https://imgur.com/zzu42ke)

[Cuando se está compartiendo la pantalla](https://imgur.com/pZ1Hgwb)

Al instalar OBS me deja seleccionar la pantalla de manera normal, espero que puedan ayudarme, **muchas gracias.**

**Comment by javierluque96** [comment]
Por lo pronto la única solución que he encontrado es utilizar discord o meet desde Chrome cuando quiero compartir pantalla, ya que desde aquí sí que me deja compartir únicamente una pantalla. Desde Firefox y desde la app de discord, me ocurre lo mismo, me comparte ambas pantallas.

**Comment by edwz-dev** [comment]
Qué raro, será usar chrome de nuevo, por ahora instalaré el chrome y probaré haber que tal, gracias por responder!

**Comment by edwz-dev** [comment]
Qué raro, será usar chrome de nuevo, por ahora instalaré el chrome y probaré haber que tal, gracias por responder!

**Comment by edwz-dev** [comment]
Estoy probando desde google en meet, todo perfecto, sigo sin entender a qué se debe este problema ya que en discord me ocurre lo mismo, gracias por tu ayuda.
