### ISSUE TITLE
How to edit the color scheme for qtile?

### ISSUE THREAD

**Issue by khang33k** [antoniosarosi/dotfiles#29]
I see you have themes folder and different json files for color schemes. 
But I can't figure out the different colors that are used like color1, color2, color3, color4 
and the dark, grey and light color as well. 
As usually, the names are different. 
Can you tell how to edit these files for a different color scheme?
Thanks!

**Comment by antoniosarosi** [comment]
naming is not the best, I'll change it when I have time but for now the only way to know which color is which is testing it manually, you can use colors like `#FF0000` or `#00FF00` to see exactly where they are applied
