### ISSUE TITLE
Gtk Configuration

### ISSUE THREAD

**Issue by AlphaTechnolog** [antoniosarosi/dotfiles#31]
Hi @antoniosarosi! very good work on your dotfiles, your dotfiles are very beautiful! congratulations!!!

But I want to know what are your gtk configuration, it's possible? more specifically your cursor theme of
your gtk configuration, you can share it configuration?

**Comment by antoniosarosi** [comment]
https://github.com/antoniosarosi/dotfiles#gtk-theming

**Comment by AlphaTechnolog** [comment]
Thank you for the fast response!
