### ISSUE TITLE
Tripple monitor setup not working

### ISSUE THREAD

**Issue by redigaffi** [antoniosarosi/dotfiles#32]
Hello, 

Tripple monitor setup is not working due to how secondary_widgets is used in the bars. Basically with the code you are passing same reference of secondary_widgets to the new bars which doesn't work. A fix that works for me is wrapping the secondary_widgets into a function returning a new copy of the widgets on every call.

`
def secondary_widgets():
     return [...]
`

When I have some time I will submit a PR.

**Comment by antoniosarosi** [comment]
I know, I made the same fix on another branch but I didn't push it yet. Submit PR and I'll merge it.

**Comment by antoniosarosi** [comment]
Fixed here: https://github.com/antoniosarosi/dotfiles/tree/arco/.config/qtile
(Not merged into master yet)
