### ISSUE TITLE
Deprecated Rofi theme definition

### ISSUE THREAD

**Issue by ACenTe25** [antoniosarosi/dotfiles#33]
First of all thanks for the amazing guide you've put together.

I found an issue with a deprecated theme definition in the Rofi configuration file (config.rasi):

`theme: "onedark";` should be replaced with `@theme: "onedark"` at the end of the file, outside of the brackets. Sorry I'm not fixing it myself, I'm not very acquainted with git.

**Comment by antoniosarosi** [comment]
Fixed here: https://github.com/antoniosarosi/dotfiles/tree/arco/.config/rofi/config.rasi
(Not merged into master yet)
