### ISSUE TITLE
Missing section in GTK3 settings.ini

### ISSUE THREAD

**Issue by ACenTe25** [antoniosarosi/dotfiles#34]
Hi,

Found another issue. The GTK and icons theme isn't loaded because there's a warning saying that the file doesn't start with a section definition.

In order to fix, the settings.ini file should start with `[Settings]` in the first line. I'm not sure if there's a similar situation with the GTK2 configuration, but it would be worth looking into it.

**Comment by antoniosarosi** [comment]
Right, I think I forgot to include it in the README file, the actual `settings.ini` is not tracked with Git. I think it's easier to use the `lxappearance` package instead of editing the GTK files manually.
