### ISSUE TITLE
Qtile unresponseive after restart

### ISSUE THREAD

**Issue by Mike97M** [antoniosarosi/dotfiles#9]
Hi,

Not sure if this is something from your script or qtile, but I've tried it and sometimes when I restart qtile(mod+shift+r) to apply some changes or when I connect an external monitor, the application from the current workspace will be on top of every other app, and on empty workspaces too, but it's like an image, not clickable, closing the app from the original workspace or with killall doesn't help, the only way to get around this is to restart every open app that was affected.

Edit:

Here is a preview:

[https://i.imgur.com/HnlBWct.png](https://i.imgur.com/HnlBWct.png)

**Comment by antoniosarosi** [comment]
My config uses ```mod+control+r``` for restarting, I'm not sure if Qtile has a default ```mod+shift+r``` keybinding that does something different. If you're using my config, restarting after connecting a monitor should work just fine. Check the logs at ```~/.local/share/qtile/qtile.log```.

**Comment by antoniosarosi** [comment]
Maybe the problem is somewhere else, I'll give it a try if you link the repo with the modified config.

**Comment by Mike97M** [comment]
Yes, you're right, it's mod_control+r for both your config and qtile default, not sure why I said shift.

The problem is that is very hard to reproduce, it doesn't happen always, I'll try to debug more on my end maybe I find something. Also, I don't think it's related to the external monitor as sometimes it happens just after a normal restart.

Nothing useful on the logs, just this multiple times:
`2021-01-12 14:58:48,335 WARNING libqtile manager.py:maybe_restart():L269 Restarting Qtile with os.execv(...)`

There was also anoter warning, but I've solved that, the warning: `Pacman is deprecated, please use CheckUpdates`

**Comment by antoniosarosi** [comment]
Have you tried to reproduce the error with the default config?

**Comment by Mike97M** [comment]
Here is the config: https://github.com/Mike97M/dotfiles/tree/master/.config/qtile

I've used another config for a few days and didn't noticed the same error, but at the same time, there are days when I don't notice it here.


After some more testing, I finally found out what is happening, now I have to find out why.

Using `xprop` and clicking on a window that looks to be in the background as explained in the first message and shown in the screenshot, it turns out that it's actually another app, so far I was able to find Discord and Telegram clients to be in the background, not sure if they are also the cause of the bug or just an effect(maybe because they are opened in the system try but their frames are hidden), skype may have a similar behavior, but I couldn't confirm it with xprop yet.

Here is the output from `xprop`:
```
_NET_WM_STATE(ATOM) = 
_NET_WM_DESKTOP(CARDINAL) = 9
WM_STATE(WM_STATE):
		window state: Withdrawn
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 407598895
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 24
		program specified minimum size: 940 by 475
_NET_WM_ICON(CARDINAL) = 
WM_NAME(UTF8_STRING) = "#text-chat - Discord"
_NET_WM_NAME(UTF8_STRING) = "#text-chat - Discord"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 83886097, 83886098
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "discord", "discord"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 739709
WM_LOCALE_NAME(STRING) = "en_US.utf8"
WM_CLIENT_MACHINE(STRING) = "ymir"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```


So far all the have in common is: electron(as far as I'm aware they all use it), system try icons and they are all communication apps(but I think this is mostly irrelevant)

**Comment by Mike97M** [comment]
Here is the config: https://github.com/Mike97M/dotfiles/tree/master/.config/qtile

I've used another config for a few days and didn't noticed the same error, but at the same time, there are days when I don't notice it here.


After some more testing, I finally found out what is happening, now I have to find out why.

Using `xprop` and clicking on a window that looks to be in the background as explained in the first message and shown in the screenshot, it turns out that it's actually another app, so far I was able to find Discord, Skype and Telegram clients to be in the background, not sure if they are also the cause of the bug or just an effect(maybe because they are opened in the system try but their frames are hidden).

Here is the output from `xprop`:
```
_NET_WM_STATE(ATOM) = 
_NET_WM_DESKTOP(CARDINAL) = 9
WM_STATE(WM_STATE):
		window state: Withdrawn
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 407598895
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 0, 24
		program specified minimum size: 940 by 475
_NET_WM_ICON(CARDINAL) = 
WM_NAME(UTF8_STRING) = "#text-chat - Discord"
_NET_WM_NAME(UTF8_STRING) = "#text-chat - Discord"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 83886097, 83886098
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "discord", "discord"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 739709
WM_LOCALE_NAME(STRING) = "en_US.utf8"
WM_CLIENT_MACHINE(STRING) = "ymir"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```


So far all the have in common is: electron(as far as I'm aware they all use it), system try icons and they are all communication apps(but I think this is mostly irrelevant)

**Comment by Mike97M** [comment]
Well, now that I found the problem, I can also replicate in in another qtile configuration, so it's qtile, not your config, I'm sorry for all the troubles, this is a similar issue: https://github.com/qtile/qtile/issues/1861

Anyway thanks for all your help.
By the way, you're doing great work with these dotfiles, thank you for publishing them!

**Comment by raj-magesh** [comment]
I have the same problem with some Electron apps installed via Flatpak (if that makes a difference): Slack and Element. The windows suddenly disappear but show my wallpaper behind them, as though the opacity has been turned down to 0. After a while, they tend to come back without my doing anything.
